# Generated by Django 5.1 on 2026-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Full Name')),
                ('organization', models.CharField(blank=True, default='', help_text='Practice, pharmacy, or company name', max_length=255)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_number', models.CharField(blank=True, default='', help_text='Your customer number at suppliers', max_length=100, verbose_name='Customer Number')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
